### ISSUE TITLE
PURL for FM-A1.1 is broken

### ISSUE THREAD

**Issue by dcfcjcheadle** [FAIRMetrics/Metrics#70] opened 2020-04-20 13:56 UTC
In reviewing several of the Gen1 FAIR Metrics, I noticed that the PURL for Metric A1.1 appears to be broken.  The posted link is as follows:
https://purl.org/fair-metrics/FM_A1.1

In keeping with the pattern for other PURLs, it should resolve to:
https://raw.githubusercontent.com/FAIRMetrics/Metrics/master/FM_A1.1

This appeared to be known in #55 but was not resolved due to an issue with the purl.org admin interface.

**Comment by markwilkinson** [comment] 2020-07-14 12:58
Unfortunately, the problem is with a purl that we are unable to edit.  This is the only one that is broken.  There seems to be nothing we can do about it without admin help from purl.org themselves (and this isn't forthcoming)

Tagging as "wont fix" as it is unfixable, for the moment.

**Closed by markwilkinson** 2020-07-14 12:58 UTC
Labels: bug, wontfix

**Comment by micheldumontier** [comment] 2020-07-14 13:03
i've sent another email to the internet archive. let's hope somebody responds!
